//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceData.Models
{
    using MySql.Data.Entity;
    using MySql.Data.MySqlClient;
    using System;
    using System.Data.Entity;

    public class MyConfiguration : DbConfiguration
    {
        public MyConfiguration()
        {
            SetExecutionStrategy("MySql.Data.MySqlClient", () => new MySqlExecutionStrategy());
            SetDefaultConnectionFactory(new MySqlConnectionFactory());
            SetProviderFactory("MySql.Data.MySqlClient", new MySqlClientFactory());
            SetProviderServices("MySql.Data.MySqlClient", new MySqlProviderServices());
        }
    }

    //[DbConfigurationType(typeof(MyConfiguration))]
    public partial class CarServiceEntities : DbContext
    {  
        public CarServiceEntities()
        : base("name=CarServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            //throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Order> Order { get; set; }
    }
}
