//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceData.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [Serializable]
    public partial class Order
    {
        [Key]
        public int IdOrder { get; set; }
        public string Title { get; set; }
        public System.DateTime BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public float Cost { get; set; }
        public int CarId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
